<a href="https://colab.research.google.com/github/sumithkumar2001/Neural-HW-2/blob/main/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Question 2

import numpy as np

# Define 5x5 input matrix
input_matrix = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
], dtype=np.float32)

# Define 3x3 kernel
kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
], dtype=np.float32)

# Function to perform convolution manually
def convolve2d(input_matrix, kernel, stride, padding):
    input_size = input_matrix.shape[0]
    kernel_size = kernel.shape[0]

    if padding == 'same':
        pad_size = kernel_size // 2
        input_matrix = np.pad(input_matrix, pad_size, mode='constant', constant_values=0)
    else:
        pad_size = 0

    output_size = ((input_size + 2 * pad_size - kernel_size) // stride) + 1
    output = np.zeros((output_size, output_size))

    for i in range(0, output_size * stride, stride):
        for j in range(0, output_size * stride, stride):
            output[i // stride, j // stride] = np.sum(
                input_matrix[i:i+kernel_size, j:j+kernel_size] * kernel
            )

    return output

# Perform convolution with different parameters
results = {
    "Stride = 1, Padding = 'VALID'": convolve2d(input_matrix, kernel, stride=1, padding='valid'),
    "Stride = 1, Padding = 'SAME'": convolve2d(input_matrix, kernel, stride=1, padding='same'),
    "Stride = 2, Padding = 'VALID'": convolve2d(input_matrix, kernel, stride=2, padding='valid'),
    "Stride = 2, Padding = 'SAME'": convolve2d(input_matrix, kernel, stride=2, padding='same'),
}

# Print output feature maps
for key, value in results.items():
    print(f"\n{key}:")
    print(value)



Stride = 1, Padding = 'VALID':
[[-6. -6. -6.]
 [-6. -6. -6.]
 [-6. -6. -6.]]

Stride = 1, Padding = 'SAME':
[[ -9.  -4.  -4.  -4.  13.]
 [-21.  -6.  -6.  -6.  27.]
 [-36.  -6.  -6.  -6.  42.]
 [-51.  -6.  -6.  -6.  57.]
 [-39.  -4.  -4.  -4.  43.]]

Stride = 2, Padding = 'VALID':
[[-6. -6.]
 [-6. -6.]]

Stride = 2, Padding = 'SAME':
[[ -9.  -4.  13.]
 [-36.  -6.  42.]
 [-39.  -4.  43.]]


In [2]:
# Question 3

import numpy as np
import cv2

# Task 1: Edge Detection Using Sobel Filter

def apply_sobel_filter(image_path):
    # Load a grayscale image
    image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

    if image is None:
        print("Error: Unable to load image.")
        return

    # Apply Sobel filter in x and y directions
    sobel_x = cv2.Sobel(image, cv2.CV_64F, 1, 0, ksize=3)
    sobel_y = cv2.Sobel(image, cv2.CV_64F, 0, 1, ksize=3)

    # Display images
    cv2.imshow("Original Image", image)
    cv2.imshow("Sobel-X", sobel_x)
    cv2.imshow("Sobel-Y", sobel_y)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

# Task 2: Max Pooling and Average Pooling using NumPy

def max_pooling(input_matrix, pool_size):
    stride = pool_size
    output_size = input_matrix.shape[0] // pool_size
    output = np.zeros((output_size, output_size))

    for i in range(0, output_size * stride, stride):
        for j in range(0, output_size * stride, stride):
            output[i // stride, j // stride] = np.max(input_matrix[i:i+pool_size, j:j+pool_size])

    return output

def average_pooling(input_matrix, pool_size):
    stride = pool_size
    output_size = input_matrix.shape[0] // pool_size
    output = np.zeros((output_size, output_size))

    for i in range(0, output_size * stride, stride):
        for j in range(0, output_size * stride, stride):
            output[i // stride, j // stride] = np.mean(input_matrix[i:i+pool_size, j:j+pool_size])

    return output

# Generate a random 4x4 matrix
input_matrix = np.random.rand(4, 4).astype(np.float32)

# Perform pooling operations
max_pooled_matrix = max_pooling(input_matrix, pool_size=2)
avg_pooled_matrix = average_pooling(input_matrix, pool_size=2)

# Print results
print("Original Matrix:")
print(input_matrix)
print("\nMax Pooled Matrix:")
print(max_pooled_matrix)
print("\nAverage Pooled Matrix:")
print(avg_pooled_matrix)

# Example usage:
# apply_sobel_filter("sample_image.jpg")


Original Matrix:
[[0.13299738 0.8356325  0.86944187 0.9083932 ]
 [0.08752741 0.07467881 0.2866109  0.3991452 ]
 [0.16771634 0.6084016  0.46754557 0.97066134]
 [0.4280672  0.35080415 0.9623563  0.31349996]]

Max Pooled Matrix:
[[0.8356325  0.9083932 ]
 [0.6084016  0.97066134]]

Average Pooled Matrix:
[[0.28270903 0.61589777]
 [0.38874733 0.67851579]]


In [4]:
# Question 4

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, Add
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import Input


# Task 1: AlexNet

def create_alexnet():
    model = Sequential([
        Conv2D(96, (11, 11), strides=4, activation='relu', input_shape=(227, 227, 3)),
        MaxPooling2D((3, 3), strides=2),
        Conv2D(256, (5, 5), activation='relu'),
        MaxPooling2D((3, 3), strides=2),
        Conv2D(384, (3, 3), activation='relu'),
        Conv2D(384, (3, 3), activation='relu'),
        Conv2D(256, (3, 3), activation='relu'),
        MaxPooling2D((3, 3), strides=2),
        Flatten(),
        Dense(4096, activation='relu'),
        Dropout(0.5),
        Dense(4096, activation='relu'),
        Dropout(0.5),
        Dense(10, activation='softmax')
    ])
    return model

alexnet_model = create_alexnet()
alexnet_model.summary()


# Task 2: ResNet

def residual_block(input_tensor, filters):
    x = Conv2D(filters, (3, 3), activation='relu', padding='same')(input_tensor)
    x = Conv2D(filters, (3, 3), padding='same')(x)
    x = Add()([x, input_tensor])
    x = tf.keras.layers.Activation('relu')(x)
    return x


def create_resnet():
    input_tensor = Input(shape=(224, 224, 3))
    x = Conv2D(64, (7, 7), strides=2, activation='relu', padding='same')(input_tensor)
    x = residual_block(x, 64)
    x = residual_block(x, 64)
    x = Flatten()(x)
    x = Dense(128, activation='relu')(x)
    output_tensor = Dense(10, activation='softmax')(x)
    model = Model(inputs=input_tensor, outputs=output_tensor)
    return model

resnet_model = create_resnet()
resnet_model.summary()


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_10 (Conv2D)                   │ (None, 55, 55, 96)          │          34,944 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_3 (MaxPooling2D)       │ (None, 27, 27, 96)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_11 (Conv2D)                   │ (None, 23, 23, 256)         │         614,656 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_4 (MaxPooling2D)       │ (None, 11, 11, 256)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_12 (Conv2D)                   │ (None, 9, 9, 384)           │         885,120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_13 (Conv2D)                   │ (None, 7, 7, 384)           │       1,327,488 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_14 (Conv2D)                   │ (None, 5, 5, 256)           │         884,992 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_5 (MaxPooling2D)       │ (None, 2, 2, 256)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_2 (Flatten)                  │ (None, 1024)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 4096)                │       4,198,400 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 4096)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 4096)                │      16,781,312 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_3 (Dropout)                  │ (None, 4096)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 10)                  │          40,970 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 24,767,882 (94.48 MB)

 Trainable params: 24,767,882 (94.48 MB)

 Non-trainable params: 0 (0.00 B)

Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer_3             │ (None, 224, 224, 3)    │              0 │ -                      │
│ (InputLayer)              │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ conv2d_15 (Conv2D)        │ (None, 112, 112, 64)   │          9,472 │ input_layer_3[0][0]    │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ conv2d_16 (Conv2D)        │ (None, 112, 112, 64)   │         36,928 │ conv2d_15[0][0]        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ conv2d_17 (Conv2D)        │ (None, 112, 112, 64)   │         36,928 │ conv2d_16[0][0]        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ add_2 (Add)               │ (None, 112, 112, 64)   │              0 │ conv2d_17[0][0],       │
│                           │                        │                │ conv2d_15[0][0]        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ activation_2 (Activation) │ (None, 112, 112, 64)   │              0 │ add_2[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ conv2d_18 (Conv2D)        │ (None, 112, 112, 64)   │         36,928 │ activation_2[0][0]     │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ conv2d_19 (Conv2D)        │ (None, 112, 112, 64)   │         36,928 │ conv2d_18[0][0]        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ add_3 (Add)               │ (None, 112, 112, 64)   │              0 │ conv2d_19[0][0],       │
│                           │                        │                │ activation_2[0][0]     │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ activation_3 (Activation) │ (None, 112, 112, 64)   │              0 │ add_3[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ flatten_3 (Flatten)       │ (None, 802816)         │              0 │ activation_3[0][0]     │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_8 (Dense)           │ (None, 128)            │    102,760,576 │ flatten_3[0][0]        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_9 (Dense)           │ (None, 10)             │          1,290 │ dense_8[0][0]          │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 102,919,050 (392.61 MB)

 Trainable params: 102,919,050 (392.61 MB)

 Non-trainable params: 0 (0.00 B)